### Create a product
POST http://localhost:8080/test-1/product/
Content-Type: application/json

{
  "name": "SmartPC",
  "price": 12.0,
  "image": "hehe",
  "productYear": 2000,
  "categoryId": 1
}

### Account register 
POST http://localhost:8080/test-1/register
Content-Type: application/json

{
  "username": "hungdeptrai",
  "password": "hung123@"
}

### Login
POST http://localhost:8080/test-1/login
Content-Type: application/json

{
  "username": "hungdeptrai",
  "password": "hung123@"
}

### Logout 
POST http://localhost:8080/test-1/logout

### Login with Staff account
POST http://localhost:8080/test-1/login
Content-Type: application/json

{
  "username": "staff",
  "password": "staff"
}
